### ISSUE TITLE
[NHÓM 14 GÓP Ý ĐỀ TÀI CHO NHÓM 15]-[LẦN 01]

### ISSUE THREAD

**Issue by dpnam** [hxtruong/DataScienceFinalProject#2]
Chào nhóm 15, mình là Đặng Phương Nam thành viên nhóm 14, theo mình hiểu thì đề tài của các bạn dự đoán giá của một laptop hay tablet dựa vào thông tin cấu hình (CPU, RAM, GPU,...) mà người dùng cung cấp. Mình có thắc mắc là:

- Khi user biết được các chi tiết cấu hình đó thì hoàn toàn có thể tự mình tra cứu giá tiền của chúng trên internet, rồi cộng lại sẽ ra được giá của cái laptop hay tablet mà mình cần build. Việc này có vẻ hiệu và chính xác hơn, thậm chí có thể giúp họ tiết kiệm được một phần chí phí (do giảm giá, phù hợp với túi tiền của user). Như thế thì user sẽ không cần đến một mô hình dự đoán giá laptop như thế nữa!.
- Ở đa số các trang web bán về laptop, tablet thì user hoàn toàn có thể lựa chọn các cấu hình (hãng, RAM, CPU, thậm chí là khoảng giá tiền,...) và thông qua các thuật toán tìm kiếm (search) thì trang web vẫn có thể trả ra các thiết bị tương xứng (có cả các sản phẩm mới vừa lên kệ mở bán). Vậy đề tài của bạn có thể hoạt động tốt hơn trong vấn đề này không?

Chúc nhóm 15 làm tốt đề tài của mình.
Thân.

**Comment by hxtruong6** [comment]
Chào bạn,
Mình trả lời 2 thắc mắc của nhóm mình như sau:

- Mục tiêu của nhóm là người dùng sẽ tự build sản phẩm từ những linh kiện khác nhau nên người dùng không cần phải tra cứu từng linh kiện để lắp ráp. Người dùng có thể tự tìm kiếm các link kiện nhưng đó là với người dùng có kiến thức nhất định về các cấu hình máy (loại nào, hãng nào, thế hệ nào,..). Vì vậy, mô hình sẽ tốt cho (a) tiết kiệm thời gian tìm kiếm từng thành phần cấu hình laptop một cách chi tiết nhưng vẫn có thể có chi phí tối ưu và (b) dễ sử dụng với những người dùng có không có kiến thức chi tiết về cấu hình laptop đã có sẵn trong bộ dữ liệu
- Mô hình của mình sẽ thực sự không tốt trong trường hợp khi có các sản phẩm linh kiện laptop mới cập nhập. Mô hình cần phải được train lại. Còn về các thuật toán tìm kiếm (tạm gọi là web search) thường sẽ chỉ tốt trên 1 website đó. Với các web khác nhau sẽ có cách web search khác nhau nên giá của sản phảm được build sẽ không được tối ưu và giao động tùy vào cách người bán hàng. Câu hỏi vẫn thường được đặt ra là làm sao biết web đó bán hàng với linh kiện giá vậy có ổn (giá quá cao hoặc quá thấp) hay không? Vì vậy cần phải cần có một giá được coi làm tham khảo thì mô hình của mình sẽ dự đoán tốt trong trường hợp này.
Cảm ơn nhóm bạn nhận xét và chúc bạn làm tốt đồ án cuối kì.
Trường.

**Comment by nghialm269** [comment]
Chào nhóm, mình là Lê Minh Nghĩa (nhóm 14)

>         Input: các thông tin của mấy tính: hãng, CPU, ram, ...
>         Output: Giá sản phẩm.

Cho mình hỏi `hãng` ở đây là hãng của laptop/tablet hay là hãng của từng linh kiện (CPU thì có Intel/AMD, ổ cứng thì có WD/SamSung, ...)?

Bạn có thể cho mình 1 record input mẫu để mình dễ hình dung được không?

**Comment by hxtruong6** [comment]
Hi bạn, 
Hãng ở đây hãng của 1 laptop. 1 laptop thì có nhiều linh kiện khác nhau và có thể hãng laptop đó mua linh kiện từ nhiều hãng linh kiện khác nhau (tùy vào nhà sản xuất).
![Screenshot from 2019-12-15 11-11-44](https://user-images.githubusercontent.com/24609363/70857997-bfca9180-1f2b-11ea-8bc2-2c381fdd0781.png)
Cơ bản 1 record của mình sẽ như này (chưa được clean).
Cảm ơn bạn đã phản hồi,
Trường
