### ISSUE TITLE
[NHÓM 14 GÓP Ý ĐỀ TÀI CHO NHÓM 15]-[LẦN 02]

### ISSUE THREAD

**Issue by dpnam** [hxtruong/DataScienceFinalProject#3]
Chào các bạn, nhóm bạn cho mình hỏi:

Theo như phần mô tả đề tài, các bạn muốn dự đoán giá của sản phẩm máy tính (bài toán Regression) khi có các thông tin input ( hãng, CPU, ram, ...). Nhưng mình không hiểu,  ở phần tiền xử lý dữ liệu: Vì sao phần giá sản phẩm (ouput), các bạn lại chia theo khoảng tiền (5 khoảng)? Về sau, ở phần mô hình hóa dữ liệu: Các bạn lại áp dụng các mô hình phân lớp (Classification)?.

Thanks.

**Comment by nghialm269** [comment]
Chào các bạn, ở phần mô hình hóa dữ liệu: 
- Mình không rõ lắm, ở mỗi mô hình phần lớp mà các bạn triển khai, các bạn có thể giải thích sơ lược về ý nghĩa của các siêu tham số và sự ảnh hưởng của chúng (tăng/giảm) là như thế nào đến kết quả?
- Theo mình quan sát kết quả độ chính xác trên tập validation cao nhất là 0.861799 tại mô hình Logistic Regression với `MaxIter` bằng 300. Vậy tại sao bạn chọn `MaxIter` bằng 500 đề fit toàn bộ tập train và dự đoán trên tập test?

**Comment by hxtruong6** [comment]
Mình xin đại diện nhóm trả lời như sau:
- Tại sao nhóm mình đổi là vì dữ liệu không đủ để nó nhận diện predict được giá thật sự gần với giá của sản phẩm. Bạn đó có thể xem mấy model demo của mình trong model_old.ipynb. Dữ liệu mình rác quá nhiều nên nó không đủ tổng quát, có nhiều thuộc tính nhưng lại nhiều giá trị null..
- Về thuộc tính thì chỉ có verbose là option cho việc hiển thị ra màn hình quá trình train-dễ theo dõi quá trình train, n_jobs là chạy trên nhiều core thôi (số core cpu - càng nhiều train càng nhanh), max_iter ,... thì bình thường
- Còn về `MaxIter` mình để là 300 đó. Chắc tại do mình chưa sửa lại.
Cảm ơn câu hỏi các bạn.
